### ISSUE TITLE
[Karaoke Dev] Peça sua música! 

### ISSUE THREAD

**Issue by jayferreira** [alfredo1995/REST#68]
https://www.youtube.com/watch?v=-70gvWNOQvc
Evidências - Chitãozinho e Xororó 

![image](https://user-images.githubusercontent.com/44149297/171236301-0a0554a2-5137-4ba1-ac8e-83e9f00ab07b.png)

**Comment by carlosmeds** [comment]
https://youtu.be/19NkU_fvF7w
